Controllers/LectureController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows;
using ITClassWeb.DAL;
using ITClassWeb.Models;

namespace ITClassWeb.Controllers
{
    public class LectureController : Controller
    {
        private ClassContext db = new ClassContext();

        // GET: Lecture
        public ActionResult Index()
        {
            var lectures = db.Lectures.Include(l => l.Member);
            return View(lectures.ToList());
        }

        // GET: Lecture/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = db.Lectures.Find(id);


            if (lecture == null)
            {
                return HttpNotFound();
            }

            ViewBag.LectureID = lecture.LectureID;

            return View(lecture);
        }

        // GET: Lecture/Create
        public ActionResult Create()
        {
            if(Session["MemberID"] != null)
            {
                ViewBag.MemberID = (int)Session["MemberID"];
                return View("Create");
            }
            else
            {
            MessageBox.Show("로그인을 하셔야 작성하실 수 있습니다.");
            return RedirectToAction("Index");

            }
           // ViewBag.MemberID = new SelectList(db.Members, "MemberID", "MemberName");
        }

        public ActionResult LectureBoardList(string lectureLanguage)
        {

            var lectures = db.Lectures.Where(l => l.LectureLanguage == lectureLanguage);


            if (lectures == null)
            {
                return HttpNotFound();
            }

            return View(lectures.ToList());
        }

       




        // POST: Lecture/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LectureID,LectureTitle,LectureLanguage,LectureImage,LectureImageName,LectureImageType,TutorIntroduce,LectureIntroduce,LecturePeople,LecturePlan,LectureCount,LecturePrice,LectureMaxperson,LectureApplyDeadline,LectureLocation,LecturePlace,ScheduleTime,MemberID")] Lecture lecture, HttpPostedFileBase image = null)
        {

            if (ModelState.IsValid)
            {

                if (image != null)
                {
                    string pic = System.IO.Path.GetFileName(image.FileName);
                    string path = System.IO.Path.Combine(
                                           Server.MapPath("~/Images/"), pic);
                    image.SaveAs(path);


                    lecture.LectureImageName = image.FileName; // 파일명
                    lecture.LectureImageType = image.ContentType;
                   
                    lecture.LectureImage = new byte[image.ContentLength];
                    

                    image.InputStream.Read(lecture.LectureImage, 0, image.ContentLength);

                }

                    db.Lectures.Add(lecture);
                    db.SaveChanges();


                var max = db.Lectures.OrderByDescending(p => p.LectureID).FirstOrDefault().LectureID;


                Session["LectureID"] = max.ToString();
                   

                return RedirectToAction("Index");
                 
            }

            return View();
        }

        public FileContentResult GetImage(int LectureID)
        {
            Lecture lecture = db.Lectures.FirstOrDefault(p => p.LectureID == LectureID);
            if (lecture != null)
                return File(lecture.LectureImage, lecture.LectureImageName);
            else
                return null;
        }




        // GET: Lecture/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Lecture lecture = db.Lectures.Find(id);

            lecture.ScheduleTime = "";


            if (lecture == null)
            {
                return HttpNotFound();
            }
            
            if(lecture.MemberID == (int)Session["MemberID"])
            {

                return View(lecture);
            }
            else
            {
                MessageBox.Show("해당 글의 작성자만 수정이 가능합니다.");
                return View();
            }
        }


        // POST: Lecture/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LectureID,LectureTitle,LectureLanguage,LectureImage,LectureImageName,LectureImageType,TutorIntroduce,LectureIntroduce,LecturePeople,LecturePlan,LectureCount,LecturePrice,LectureMaxperson,LectureApplyDeadline,LectureLocation,LecturePlace,ScheduleTime,MemberID")] Lecture lecture, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    string pic = System.IO.Path.GetFileName(image.FileName);
                    string path = System.IO.Path.Combine(
                                           Server.MapPath("~/Images/"), pic);

                    image.SaveAs(path);
                    lecture.LectureImageName = image.FileName; // 파일명
                    lecture.LectureImageType = image.ContentType;

                    lecture.LectureImage = new byte[image.ContentLength];


                    image.InputStream.Read(lecture.LectureImage, 0, image.ContentLength);

                }
                db.Entry(lecture).State = EntityState.Modified;

                db.SaveChanges();

                return RedirectToAction("Index");
            }

          
            return View(lecture);
        }


        // GET: Lecture/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = db.Lectures.Find(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            return View(lecture);
        }





        // POST: Lecture/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lecture lecture = db.Lectures.Find(id);
            db.Lectures.Remove(lecture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


      




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Learn Programming Language!</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IT Taling", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ar-auto">
              
                    <li>@Html.ActionLink("Members", "Index", "Member")</li>
                    <li>@Html.ActionLink("Lectures", "Index", "Lecture")</li>
                    <li>@Html.ActionLink("C", "LectureBoardList", "Lecture", new { LectureLanguage = "C" }, null)</li>
                    <li>@Html.ActionLink("C++", "LectureBoardList", "Lecture", new { LectureLanguage = "C++" }, null)</li>
                    <li>@Html.ActionLink("C#", "LectureBoardList", "Lecture", new { LectureLanguage = "C#" }, null)</li>
                    <li>@Html.ActionLink("JAVA", "LectureBoardList", "Lecture", new { LectureLanguage = "JAVA" }, null)</li>
                    <li>@Html.ActionLink("HTML", "LectureBoardList", "Lecture", new { LectureLanguage = "HTML" }, null)</li>
                    <li>@Html.ActionLink("CSS", "LectureBoardList", "Lecture", new { LectureLanguage = "CSS" }, null)</li>
                    <li>@Html.ActionLink("JAVASCRIPT", "LectureBoardList", "Lecture", new { lectureLanguage = "JAVASCRIPT" }, null)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["MemberID"] == null)
                    {
                        <li>@Html.ActionLink("Sign up", "Create", "Member", new { }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Sign in", "SignIn", "Member", new { }, new { @class = "navbar-brand" })</li>
                    }

                    else
                    {
                        <li>@Html.ActionLink((string)(Session["MemberEmail"]), "Edit", "Member", new { }, new { @class = "navbar-brand" })</li>
                        <li>@Html.ActionLink("Sign out", "SignOut", "Member", new { }, new { @class = "navbar-brand" })</li>
                    }
                    @if ((string)(Session["MemberType"]) == ("일반"))
                    {
                        <li>@Html.ActionLink("Register as Tutor", "TutorRegister", "Member", new { id = Session["MemberID"] }, new { @class = "navbar-brand" })</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        
        <footer class="w3-container w3-padding-32 w3-light-grey w3-center w3-xlarge">
            <div class="w3-section">
                <i class="fa fa-facebook-official w3-hover-opacity"></i>
                <i class="fa fa-instagram w3-hover-opacity"></i>
                <i class="fa fa-snapchat w3-hover-opacity"></i>
                <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                <i class="fa fa-twitter w3-hover-opacity"></i>
                <i class="fa fa-linkedin w3-hover-opacity"></i>
            </div>
            <p class="w3-medium">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>